providers:
  file:
    directory: /etc/traefik/conf.d
entryPoints:
  web:
    address: :80
  #websecure:
  #  address: :443
  #grpc:
  #  address: :8000
  #registry:
  #  address: :5800

api:
  insecure: true
  dashboard: true
log:
  level: DEBUG
serversTransport:
  insecureSkipVerify: true